# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Corse Enroll Hub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Corse Enroll Hub
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  pod 'Firebase/DatabaseSwift'


  target 'Corse Enroll HubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Corse Enroll HubUITests' do
    # Pods for testing
  end

end
